##################################
##  Hide low quality items
##################################
Hide
	Rarity Normal Magic
	Class == "Shields" "Claws" "Daggers" "One Hand Axes" "One Hand Maces" "Thrusting One Hand Swords" "One Hand Swords" "Rune Daggers" "Sceptres" "Wands"
Hide
	Rarity Normal Magic
	Class == "Gloves" "Boots" "Helmets"
Hide
	Rarity Normal Magic
	Class == "Body Armours" "Two Hand Axes" "Two Hand Maces" "Two Hand Swords" "Warstaves" "Bows" "Staves"
	Sockets < "6"
Hide
	Rarity Normal Magic
	Class == "Amulets" "Belts" "Rings" "Quivers" "Utility Flasks" "Life Flasks" "Mana Flasks" "Jewels"

