##################################
##  Hide Armor - Evasion
##################################
Hide
	Rarity Normal Magic Rare
	Class == "Body Armours"
	BaseType "Shabby Jerkin" "Strapped Leather" "Buckskin Tunic" "Wild Leather" "Full Leather" "Sun Leather" "Thief's Garb" "Eelskin Tunic" "Frontier Leather" "Glorious Leather" "Coronal Leather" "Cutthroat's Garb" "Sharkskin Tunic" "Destiny Leather" "Exquisite Leather" "Zodiac Leather" "Assassin's Garb" "Supreme Leather" "Astral Leather" "Syndicate's Garb"
Hide
	Rarity Normal Magic Rare
	Class == "Gloves"
	BaseType "Rawhide Gloves" "Goathide Gloves" "Deerskin Gloves" "Nubuck Gloves" "Eelskin Gloves" "Sharkskin Gloves" "Shagreen Gloves" "Stealth Gloves" "Slink Gloves" "Gripped Gloves" "Harpyskin Gloves" "Velour Gloves"
Hide
	Rarity Normal Magic Rare
	Class == "Boots"
	BaseType "Rawhide Boots" "Goathide Boots" "Deerskin Boots" "Nubuck Boots" "Eelskin Boots" "Sharkskin Boots" "Shagreen Boots" "Stealth Boots" "Slink Boots" "Harpyskin Boots" "Velour Boots"
Hide
	Rarity Normal Magic Rare
	Class == "Helmets"
	BaseType "Leather Cap" "Tricorne" "Leather Hood" "Wolf Pelt" "Hunter Hood" "Noble Tricorne" "Ursine Pelt" "Silken Hood" "Sinner Tricorne" "Lion Pelt" "Dire Pelt" "Grizzly Pelt" "Majestic Pelt"
Hide
	Rarity Normal Magic Rare
	Class == "Shields"
	BaseType "Goathide Buckler" "Pine Buckler" "Painted Buckler" "Hammered Buckler" "War Buckler" "Gilded Buckler" "Oak Buckler" "Enameled Buckler" "Corrugated Buckler" "Battle Buckler" "Golden Buckler" "Ironwood Buckler" "Lacquered Buckler" "Vaal Buckler" "Crusader Buckler" "Imperial Buckler"

