##################################
##  Hide Armor - Energy Shield + Armor
##################################
Hide
	Rarity Normal Magic Rare
	Class == "Body Armours"
	BaseType "Chainmail Vest" "Chainmail Tunic" "Ringmail Coat" "Chainmail Doublet" "Full Ringmail" "Full Chainmail" "Holy Chainmail" "Latticed Ringmail" "Crusader Chainmail" "Ornate Ringmail" "Chain Hauberk" "Devout Chainmail" "Loricated Ringmail" "Conquest Chainmail" "Elegant Ringmail" "Saint's Hauberk" "Saintly Chainmail" "Grand Ringmail" "Paladin's Hauberk" "Sacred Chainmail"
Hide
	Rarity Normal Magic Rare
	Class == "Gloves"
	BaseType "Chain Gloves" "Ringmail Gloves" "Mesh Gloves" "Riveted Gloves" "Zealot Gloves" "Soldier Gloves" "Legion Gloves" "Crusader Gloves" "Martyr Gloves" "Paladin Gloves" "Apothecary's Gloves"
Hide
	Rarity Normal Magic Rare
	Class == "Boots"
	BaseType "Chain Boots" "Ringmail Boots" "Mesh Boots" "Riveted Boots" "Zealot Boots" "Soldier Boots" "Legion Boots" "Crusader Boots" "Two-Toned Boots" "Martyr Boots" "Paladin Boots"
Hide
	Rarity Normal Magic Rare
	Class == "Helmets"
	BaseType "Rusted Coif" "Soldier Helmet" "Great Helmet" "Crusader Helmet" "Aventail Helmet" "Zealot Helmet" "Great Crown" "Magistrate Crown" "Prophet Crown" "Praetor Crown" "Bone Helmet" "Faithful Helmet" "Paladin Crown" "Divine Crown"
Hide
	Rarity Normal Magic Rare
	Class == "Shields"
	BaseType "Plank Kite Shield" "Linden Kite Shield" "Reinforced Kite Shield" "Layered Kite Shield" "Ceremonial Kite Shield" "Etched Kite Shield" "Steel Kite Shield" "Laminated Kite Shield" "Angelic Kite Shield" "Branded Kite Shield" "Champion Kite Shield" "Mosaic Kite Shield" "Archon Kite Shield"

