##################################
##  Hide Armor - Evasion + Armor
##################################
Hide
	Rarity Normal Magic Rare
	Class == "Body Armours"
	BaseType "Scale Vest" "Light Brigandine" "Scale Doublet" "Infantry Brigandine" "Full Scale Armour" "Soldier's Brigandine" "Field Lamellar" "Wyrmscale Doublet" "Hussar Brigandine" "Full Wyrmscale" "Commander's Brigandine" "Battle Lamellar" "Dragonscale Doublet" "Desert Brigandine" "Full Dragonscale" "General's Brigandine" "Triumphant Lamellar" "Full Wyvernscale" "Marshall's Brigandine" "Conquest Lamellar"
Hide
	Rarity Normal Magic Rare
	Class == "Gloves"
	BaseType "Fishscale Gauntlets" "Ironscale Gauntlets" "Bronzescale Gauntlets" "Steelscale Gauntlets" "Serpentscale Gauntlets" "Wyrmscale Gauntlets" "Hydrascale Gauntlets" "Dragonscale Gauntlets" "Chimerascale Gauntlets" "Wyvernscale Gauntlets" 
Hide
	Rarity Normal Magic Rare
	Class == "Boots"
	BaseType "Leatherscale Boots" "Ironscale Boots" "Bronzescale Boots" "Steelscale Boots" "Serpentscale Boots" "Wyrmscale Boots" "Hydrascale Boots" "Dragonscale Boots" "Chimerascale Boots" "Wyvernscale Boots" 
Hide
	Rarity Normal Magic Rare
	Class == "Helmets"
	BaseType "Battered Helm" "Sallet" "Visored Sallet" "Gilded Sallet" "Secutor Helm" "Fencer Helm" "Lacquered Helmet" "Fluted Bascinet" "Pig-Faced Bascinet" "Nightmare Bascinet" "Knight Helm" "Conquest Helmet" "Haunted Bascinet" 
Hide
	Rarity Normal Magic Rare
	Class == "Shields"
	BaseType "Rotted Round Shield" "Fir Round Shield" "Studded Round Shield" "Scarlet Round Shield" "Splendid Round Shield" "Maple Round Shield" "Spiked Round Shield" "Crimson Round Shield" "Baroque Round Shield" "Teak Round Shield" "Spiny Round Shield" "Cardinal Round Shield" "Elegant Round Shield"

