##################################
##  Hide outdated flasks
##################################
Hide
	Class == "Life Flasks" "Mana Flasks"
	BaseType "Large" "Medium" "Small"
	AreaLevel >= 15
Hide
	Class == "Life Flasks" "Mana Flasks"
	BaseType "Grand" "Greater"
	AreaLevel >= 30
Hide
	Class == "Life Flasks" "Mana Flasks"
	BaseType "Colossal" "Giant" "Sacred"
	AreaLevel >= 48
Hide
	Class == "Life Flasks" "Mana Flasks"
	BaseType "Hallowed" "Sanctified"
	AreaLevel >= 60

