##################################
##  Hide Armor - Energy Shield + Evasion
##################################
Hide
	Rarity Normal Magic Rare
	Class == "Body Armours"
	BaseType "Padded Vest" "Oiled Vest" "Padded Jacket" "Oiled Coat" "Scarlet Raiment" "Waxed Garb" "Bone Armour" "Quilted Jacket" "Sleek Coat" "Crimson Raiment" "Lacquered Garb" "Crypt Armour" "Sentinel Jacket" "Varnished Coat" "Blood Raiment" "Sadist Garb" "Carnal Armour" "Sanguine Raiment" "Torturer Garb" "Necrotic Armour"
Hide
	Rarity Normal Magic Rare
	Class == "Gloves"
	BaseType "Wrapped Mitts" "Strapped Mitts" "Clasped Mitts" "Trapper Mitts" "Ambush Mitts" "Carnal Mitts" "Assassin's Mitts" "Murder Mitts" "Infiltrator Mitts" "Phantom Mitts"
Hide
	Rarity Normal Magic Rare
	Class == "Boots"
	BaseType "Wrapped Boots" "Strapped Boots" "Clasped Boots" "Shackled Boots" "Trapper Boots" "Ambush Boots" "Carnal Boots" "Assassin's Boots" "Murder Boots" "Infiltrator Boots" "Phantom Boots" "Fugitive Boots"
Hide
	Rarity Normal Magic Rare
	Class == "Helmets"
	BaseType "Scare Mask" "Plague Mask" "Iron Mask" "Festival Mask" "Golden Mask" "Raven Mask" "Callous Mask" "Regicide Mask" "Harlequin Mask" "Vaal Mask" "Deicide Mask" "Jester Mask" "Ancient Mask" "Torturer's Mask"
Hide
	Rarity Normal Magic Rare
	Class == "Shields"
	BaseType "Spiked Bundle" "Driftwood Spiked Shield" "Alloyed Spiked Shield" "Burnished Spiked Shield" "Ornate Spiked Shield" "Redwood Spiked Shield" "Compound Spiked Shield" "Polished Spiked Shield" "Sovereign Spiked Shield" "Alder Spiked Shield" "Ezomyte Spiked Shield" "Mirrored Spiked Shield" "Supreme Spiked Shield"

