##################################
##  Show High Quality Items
##################################

Show
	SetBorderColor 200 0 200
	SetFontSize 50
	Rarity Normal Magic Rare
	Class == "Shields" "Claws" "Daggers" "One Hand Axes" "One Hand Maces" "Thrusting One Hand Swords" "One Hand Swords" "Rune Daggers" "Sceptres" "Wands"
	LinkedSockets 3
	Quality >= "1"
	MinimapIcon 1 Purple Diamond
Show
	SetBorderColor 200 0 200
	SetFontSize 50
	Rarity Normal Magic Rare
	Class == "Gloves" "Boots" "Helmets"
	LinkedSockets 4
	Quality >= "1"
	MinimapIcon 1 Purple Diamond
Show
	SetBorderColor 200 0 200
	SetFontSize 50
	Rarity Normal Magic Rare
	Class == "Body Armours" "Two Hand Axes" "Two Hand Maces" "Two Hand Swords" "Warstaves" "Bows" "Staves"
	LinkedSockets 6
	MinimapIcon 1 Purple Diamond
Show
	SetBorderColor 200 0 200
	SetFontSize 50
	Rarity Unique
	MinimapIcon 1 Orange Diamond


Show
	SetFontSize 40
	Rarity Normal Magic Rare
	Class == "Shields" "Claws" "Daggers" "One Hand Axes" "One Hand Maces" "Thrusting One Hand Swords" "One Hand Swords" "Rune Daggers" "Sceptres" "Wands"
	LinkedSockets 3
Show
	SetFontSize 40
	Rarity Normal Magic Rare
	Class == "Gloves" "Boots" "Helmets"
	LinkedSockets 4
Show
	SetFontSize 40
	Rarity Normal Magic Rare
	Class == "Body Armours" "Two Hand Axes" "Two Hand Maces" "Two Hand Swords" "Warstaves" "Bows" "Staves"
	Sockets >= "6"
Show
	SetFontSize 40
	Quality >= "1"

